name: action

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:4.4
        ports: 
        - 27017:27017

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: npm install
        working-directory: ./backend
        run: npm install
      - name: Run Tests
        working-directory: ./backend
        run: npm run test
      - name: Clear Database
        run: ./automate_mongo.sh
      - name: npm install
        working-directory: ./frontend
        run: npm install
      - name: Start backend server
        run: |
          cd backend
          npm start &
      - name: Run Cypress tests
        run: npx cypress run --spec "cypress/integration/todo.spec.js"
      - name: Clear Database
        run: ./automate_mongo.sh
